# Generated by Django 5.0.1 on 2024-02-23 05:00

import crm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('Profile_Photo', models.ImageField(blank=True, upload_to='images/', validators=[crm.models.validate_picture_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])])),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile_Number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Role', models.CharField(max_length=150)),
                ('DOB', models.DateField()),
                ('Password', models.CharField(max_length=128)),
                ('Confirm_Password', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'crm',
            },
        ),
    ]
